### ISSUE TITLE
Build for android

### ISSUE THREAD

**Issue by Herz3h** [wang-bin/avbuild#8]
Hello,

What does these tools build ? a library or an executable ? Also does it use GPL parts of ffmpeg or only LGPL ? 

I need to build FFMPEG for a commercial product on Android but the ones on the internet are built for android using GPL source code, and are not up to date (current one i use is 2.4 version)

Thanks in advance

**Comment by Herz3h** [comment]
After running the prebuild binaries on my Android 5.1 i get this output : 

$ ./ffmpeg

```
WARNING: linker: ./ffmpeg: unused DT entry: type 0x6ffffffe arg 0x3e14
WARNING: linker: ./ffmpeg: unused DT entry: type 0x6fffffff arg 0x8
1
```

It does not matter what parameter i give it, it prints that. 

I've tried ffmpeg-3.4-android-clang.tar.xz and ffmpeg-3.4-android-gcc-lite.tar.xz and ffmpeg-3.2.4-android-armv7-lite.tar.xz

It doesn't matter which one i use, it the same. I only copy the ffmpeg binary in the bin folder (armeabi-v7a and tried armeabi) but same output of all of these.

What am i doing wrong ?

**Comment by wang-bin** [comment]
> What does these tools build ? a library or an executable ? Also does it use GPL parts of ffmpeg or only LGPL ?

It's LGPL. You can use them in your commercial products. Packages with `-lite` suffix do not include all features to reduce size, but the features included are enough for most users.

> WARNING: linker: ./ffmpeg: unused DT entry: type 0x6ffffffe arg 0x3e14
> WARNING: linker: ./ffmpeg: unused DT entry: type 0x6fffffff arg 0x8

I tested on android 7.1, no such warnings. You can ignore the warnings for now. I will investigate the warnings later. My company uses the same script for android>=4.0 without any problem.

> I noticed the .a files are quit large (libavcodec 14MB) where as the ffmpeg executable is like 180ko, is this normal ??

.a files are static libs. A static libraries is usually larger than a shared library(.so) because shared libs are optimized by linker while static libs must contains all symbols to make sure linking the final executable correctly. the exectubles such as ffmpeg are linked to shared libs, so the size is small. When building your app, compiler will first try to use shared libs, if not found, static libs are used.

> WARNING: Could not find library: libavdevice.so

Tell ndk-depends where to find the libraries `ndk-depends bin/armeabi-v7a/ffmpeg -L$PWD/lib/armeabi-v7a`
